version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: emberfall
    goarm: 6
    goamd64: v1
    url_template: "https://github.com/aquia-inc/emberfall/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    url_headers:
      - "Accept: application/octet-stream"
      - 'Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}'
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: Richard Jones
      email: richard.jones@aquia.io
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    description: "Smoke testing for HTTP services made easy!"
    repository:
      owner: aquia-inc
      name: emberfall
      branch: main
      pull_request:
        enabled: true
        draft: true
      git:
        url: 'ssh://git@github.com/aquia-inc/emberfall.git'
        private_key: '{{ .Env.PRIVATE_KEY_PATH }}'
