# This file was generated by GoReleaser. DO NOT EDIT.
cask "emberfall" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "3a19a52bb714ffe5a0a05309951ecc9e14e51d7e2229175f5601bc6a7dd5c661"
      url "https://github.com/aquia-inc/emberfall/releases/download/v#{version}/emberfall_Darwin_x86_64.tar.gz",
          header: [
            "Accept: application/octet-stream",
          ]
    end
    on_arm do
      sha256 "85ffe52c2567083162f97864c2e90afee4707edf4e1379003e63780a3b64e38f"
      url "https://github.com/aquia-inc/emberfall/releases/download/v#{version}/emberfall_Darwin_arm64.tar.gz",
          header: [
            "Accept: application/octet-stream",
          ]
    end
  end

  on_linux do
    on_intel do
      sha256 "f2f873b0fe7a3ba7a174846b2fe5b266fa6c1b284570a0b48369d88fe46bcf1c"
      url "https://github.com/aquia-inc/emberfall/releases/download/v#{version}/emberfall_Linux_x86_64.tar.gz",
          header: [
            "Accept: application/octet-stream",
          ]
    end
    on_arm do
      sha256 "2239882d36340ef0144ef31f5ae099564d059597b8220a1f6527ab3a51b26248"
      url "https://github.com/aquia-inc/emberfall/releases/download/v#{version}/emberfall_Linux_arm64.tar.gz",
          header: [
            "Accept: application/octet-stream",
          ]
    end
  end

  name "emberfall"
  desc "Smoke testing for HTTP services made easy!"
  homepage "https://github.com/aquia-inc/emberfall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emberfall"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emberfall"]
    end
  end
end
