# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emberfall < Formula
  desc "Smoke testing for HTTP services made easy!"
  homepage ""
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aquia-inc/emberfall/releases/download/v0.4.1/emberfall_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "98c7d3c7aa6694eb03daeb1e4624c1600f0cd411e7ac534b3255f70a8579e3d0"

      define_method(:install) do
        bin.install "emberfall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aquia-inc/emberfall/releases/download/v0.4.1/emberfall_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "21a485bdc1aec68d28d8239caa1da5b38c6b93a207bd7bd4c164004746ad72ca"

      define_method(:install) do
        bin.install "emberfall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aquia-inc/emberfall/releases/download/v0.4.1/emberfall_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "2acde67b07676a0b786d1663fc05da07c287b4d4b4e41bc9b1579582526f2f25"
      define_method(:install) do
        bin.install "emberfall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aquia-inc/emberfall/releases/download/v0.4.1/emberfall_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "885e1a99ba505b33172f1267c7a7fc5ffc96f05b885b881efc534cb6fe82d04b"
      define_method(:install) do
        bin.install "emberfall"
      end
    end
  end
end
