# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emberfall < Formula
  desc "Smoke testing for HTTP services made easy!"
  homepage ""
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aquia-inc/emberfall/releases/download/v0.4.0/emberfall_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "d05247a6d1306467114550899c2e6bc85b6767d7124f2cdefad113645d7f1787"

      def install
        bin.install "emberfall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aquia-inc/emberfall/releases/download/v0.4.0/emberfall_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "b536234eefe93d9e0eb1e4f830b209101ee8f0a9a5c010f9659f7022fdd98094"

      def install
        bin.install "emberfall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aquia-inc/emberfall/releases/download/v0.4.0/emberfall_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "2999ff3a2052171370c094a7d42ef94db7975f81c08f3848ff602446fd50ddc3"
      def install
        bin.install "emberfall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aquia-inc/emberfall/releases/download/v0.4.0/emberfall_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "64ca1a20cfa6dce12c9e687e367179973001873c1a4555036a07d017f0fe5e9b"
      def install
        bin.install "emberfall"
      end
    end
  end
end
