name: Pipeline

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  analysis:
    name: Analysis
    uses: ./.github/workflows/analysis.yaml

  tests:
    name: Tests
    needs: analysis
    uses: ./.github/workflows/tests.yaml

  release:
    name: Release
    needs: analysis
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yaml
    secrets: inherit
