name: Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  analysis:
    name: Analysis
    uses: ./.github/workflows/analysis.yml
