name: Tests

on:
  workflow_call:

jobs:
  Lint-Go:
    name: Lint Go
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5

      - name: Compile
        run: go build -o ./ ./...

      - id: setup-bats
        uses: bats-core/bats-action@3.0.0

      - name: Test CLI
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          TERM: xterm
        run: bats tests/cli.bats
